version: '3.8'

services:
  db:
    build: .                 # สั่งให้ build จาก Dockerfile ในโฟลเดอร์นี้
    container_name: plant_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword     # รหัสผ่านของ Root
      MYSQL_DATABASE: plant_run_db          # ชื่อฐานข้อมูลที่จะสร้างอัตโนมัติ
      MYSQL_USER: plant_dev                 # ชื่อ User สำหรับให้ Node.js ใช้งาน
      MYSQL_PASSWORD: devpassword123        # รหัสผ่านของ User
    ports:
      - "3306:3306"          # แมปพอร์ต 3306 ในเครื่องเรา เข้ากับ 3306 ใน Docker
    volumes:
      - mysql_data:/var/lib/mysql  # เก็บข้อมูลไว้ในเครื่องเรา (ป้องกันข้อมูลหายตอนปิด Docker)

volumes:
  mysql_data: